In [1]:
import andi
import numpy as np
import csv as csv
import numpy as np

from sklearn.metrics import mean_absolute_error
import tensorflow as tf



import keras
from keras.models import Sequential
from keras.layers import Dense, Dropout, Activation
from keras.optimizers import SGD
from keras import losses, metrics

from keras.models import Sequential
from keras.layers import Dense
from keras.layers import SimpleRNN
from keras.layers import LSTM

from keras.layers import Dropout
from keras.layers import Bidirectional
#from keras.models import load_model
from tensorflow.keras.models import load_model
import os
from matplotlib import pyplot as plt
from data_split import data_split
from many_net import many_net, many_net_diffv, many_net_only_diff, many_net_odcv_hd

Using TensorFlow backend.


In [4]:
os.getcwd()

'/Users/stefabo/Documents/GitHub/eduRNN'

Importing the data

In [8]:
import csv
trajs_from_files = csv.reader(open('challenge_for_scoring/task2.txt','r'), delimiter=';', 
                                        lineterminator='\n',quoting=csv.QUOTE_NONNUMERIC)
validation = [[],[],[]]
for trajs in enumerate(trajs_from_files):
    validation[int(trajs[1][0])-1].append(trajs[1][1:])

In [19]:
predictions1d=np.load('task2_predictions1d_more_nets.npy')

In [3]:
predictions1d.shape

(16618, 5)

#2d case

In [20]:
predictions2d=np.load('task2_predictions2d_using2d.npy')

In [21]:
predictions2d.shape

(13309, 5)

In [22]:
pred2_num=np.argmax(predictions2d,axis=1)

In [23]:
pred2_num[5]

1

In [43]:
kk=7

In [44]:
predictions2d[kk]

array([7.3018862e-04, 1.5829311e-05, 1.2071896e-01, 8.7116998e-01,
       7.3649925e-03], dtype=float32)

In [45]:
predictions2d_u1d[kk]

array([6.7479354e-03, 7.4782643e-06, 5.2145386e-01, 1.9716774e-03,
       4.6981910e-01], dtype=float32)

In [46]:
comb[kk]

array([7.3018862e-04, 1.5829311e-05, 1.2071896e-01, 8.7116998e-01,
       7.3649925e-03], dtype=float32)

In [24]:
aa=pred2_num!=3

In [43]:
comb[aa]

array([[7.10955113e-02, 9.28892732e-01, 8.45228499e-07, 1.02566955e-05,
        7.14144221e-07],
       [2.82730162e-03, 2.95465616e-05, 4.87502098e-01, 4.89522336e-06,
        5.09636104e-01],
       [2.58082330e-01, 1.50984415e-04, 4.66389179e-01, 1.45336715e-04,
        2.75232255e-01],
       ...,
       [1.77724034e-01, 3.45109105e-01, 2.82557428e-01, 3.53250653e-02,
        1.59284353e-01],
       [5.29826768e-02, 7.82516718e-01, 1.35927528e-01, 1.18120536e-02,
        1.67610720e-02],
       [2.30676471e-03, 1.14575708e-02, 9.85278368e-01, 5.39639914e-05,
        9.03344247e-04]], dtype=float32)

In [25]:
predictions2d_u1d=np.load('task2_predictions2d_more_using2traj_1dnets.npy')

In [26]:
predictions2d_u1d.shape

(13309, 5)

In [27]:
predictions2d.shape

(13309, 5)

In [30]:
comb=predictions2d
comb[aa]=(predictions2d_u1d[aa]+predictions2d[aa])/2

In [47]:
predictions3d=np.load('task2_predictions3d.npy')

In [40]:
comb[2]

array([2.5808233e-01, 1.5098442e-04, 4.6638918e-01, 1.4533671e-04,
       2.7523226e-01], dtype=float32)

In [48]:
predictions3d.shape

(10000, 5)

In [ ]:
#combine predict

In [49]:
predictions_task2=[predictions1d,comb,predictions3d]

In [ ]:
# pred_to_txt = np.ones((len(predictions), 6))
# for i in range(len(predictions)):
#     for j in range(5):
        
#         pred_to_txt[i, j+1] = predictions[i][j]

# np.savetxt('task2.txt', pred_to_txt.astype(float), fmt = '%1.5f', delimiter = ';')

In [16]:
# #having only 2d cases
# #predictions_task2=[predictions1d,predictions2d]
# pred_to_txt = np.concatenate((np.ones((len(predictions1d), 6)),
#                               2*np.ones((len(), 6)),3*np.ones((len(predictions3d), 6))))
# for dim in [1,2,3]: 
#     for i in range(len(predictions_task2[dim-1])):
#         for j in range(5):
        
#             pred_to_txt[i+len(predictions1d)*(dim-1), j+1] = predictions_task2[dim-1][i][j]

    
# #     pred_to_txt_temp = dim*np.ones((len(predictions_task2[dim-1]), 2))
# #     pred_to_txt_temp[:, 1] = predictions_task2[dim-2]
# #     pred_to_txt.append(pred_to_txt_temp)
# np.savetxt('task2_pro.txt', pred_to_txt.astype(float), fmt = '%1.5f', delimiter = ';')

In [50]:
pred_to_txt = np.concatenate((np.ones((len(predictions1d), 6)),
                              2*np.ones((len(comb), 6)),
                              3*np.ones((len(predictions3d), 6))))
bb=0
for dim in [1,2,3]:
    dis=len(predictions_task2[dim-1])
    print(bb)
    for i in range(dis):
        for j in range(5):
            pred_to_txt[i+bb, j+1] = predictions_task2[dim-1][i][j]
    bb=bb+dis
    print(bb)
#     pred_to_txt_temp = dim*np.ones((len(predictions_task2[dim-1]), 2))
#     pred_to_txt_temp[:, 1] = predictions_task2[dim-2]
#     pred_to_txt.append(pred_to_txt_temp)
np.savetxt('task2_pro.txt', pred_to_txt.astype(float), fmt = '%1.5f', delimiter = ';')

0
16618
16618
29927
29927
39927


In [34]:
pred_to_txt[20001]

array([3.00000000e+00, 8.67642879e-01, 1.72879063e-02, 8.37111584e-05,
       1.13977821e-05, 1.14974037e-01])

In [35]:
predictions3d[]

array([8.6764288e-01, 1.7287906e-02, 8.3711158e-05, 1.1397782e-05,
       1.1497404e-01], dtype=float32)

In [ ]:
pred_to_txt = np.ones((len(predictions_comb), 6))
for i in range(len(predictions_comb)):
    for j in range(5):
        
        pred_to_txt[i, j+1] = predictions_comb[i][j]

np.savetxt('task2_comb.txt', pred_to_txt.astype(float), fmt = '%1.5f', delimiter = ';')